env: productenv22
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8762/eureka/
server:
  port: 8088
spring:
  application:
    name: product
  datasource:
    username: root
    password: 111111
    url: jdbc:mysql:///pm110u4mtwm?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.0.119
    username: guest
    password: guest
    port: 5672
